### ISSUE TITLE
Book challenge feedback

### ISSUE THREAD

**Issue by JosephCherry** [TirsaRP/hyf-javascript2#1]
Hey Tirsa, 

Great work here. Everything is well named and commented. Noticed you've created the core h2 and ul outside of the function. Perhaps you could create a separate function you call when you create this or alternatively put it inside the function with some logic so it only runs once. 

Codetastic!

**Comment by TirsaRP** [comment]
thanks for the feedback, I put the h2 and ul  code into a function.
