### ISSUE TITLE
JS 2 Wk 2 Notes 

### ISSUE THREAD

**Issue by JosephCherry** [TirsaRP/hyf-javascript2#2]
Line 20. A filter will automatically create a new array so there is no need to declare it in this line. 

Line 77. As we talked about before you've made it easier for yourself by writing in hours. Rendering the correct decimal place is perhaps worth looking up for future reference. 

Line 83. Perhaps use some more specific language for the variables in your reduce function. 

Line 85. Nice use of a toLocaleString. Not a function I've come across before. Does is also place it within to decimal places? 

Great work.

**Comment by TirsaRP** [comment]
I removed line 20. 
I will try to rework my array with minutes instead.
changed the names of the variables in line 83.
I found "toLocaleString" handy, you can read more about it here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
